(global-set-key (kbd "C-x <home>") 'anything)
(global-set-key (kbd "C-x <right>") 'anything-find-files)
(global-set-key (kbd "<home>") 'beginning-of-visual-line)
(global-set-key (kbd "C-h C-a") 'back-to-indentation)
(global-set-key (kbd "C-h <home>") 'back-to-indentation)
